/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32g0xx.h"
#include "stm32g031xx.h"
#include "SegmentController.h"

#define LEDDELAY    500000

void delay(volatile uint32_t);

int main(void) {



	//First Digit Opens PB9 connected
	/* Enable GPIOB clock */
	RCC->IOPENR |= (1U << 1);

	// SETUP PB6 AS output
	GPIOB->MODER &= ~(3U << 2*9);
	GPIOB->MODER |= (1U << 2*9);


	// led 4th digit open
	GPIOB->ODR |= (1U << 9);

	// All segments working
	SegmentController('A');
	SegmentController('B');
	SegmentController('C');
	SegmentController('D');
	SegmentController('E');
	SegmentController('F');
	SegmentController('G');
	SegmentController('O');


    return 0;
}

void delay(volatile uint32_t s) {
    for(; s>0; s--);
}
