/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32g0xx.h"
#include "stm32g031xx.h"

#define LEDDELAY    500000

void delay(volatile uint32_t);

int main(void) {


	/* Enable GPIOC clock */
    //RCC->IOPENR |= (1U << 2);

	/* Enable GPIOB clock */
	RCC->IOPENR |= (1U << 1);

	// SETUP PB6 AS output
	GPIOB->MODER &= ~(3U << 2*6);
	GPIOB->MODER |= (1U << 2*6);

	  /* Turn on LED */
	//GPIOB->ODR |= (1U << 6);


	/* Enable GPIOB clock */
	RCC->IOPENR |= (1U << 1);

	// SETUP PB6 AS output
	GPIOB->MODER &= ~(3U << 2*5);
	GPIOB->MODER |= (1U << 2*5);


	// led 4th digit open
	GPIOB->ODR |= (1U << 5);
	//led 7segment B is open
	GPIOB->ODR &= ~(1U << 6);


    return 0;
}

void delay(volatile uint32_t s) {
    for(; s>0; s--);
}
